#### Welcome

In [56]:
print('Hello!!!')

Hello!!!


In [57]:
!ls -la

total 56
drwxr-xr-x  7 vladislav  staff    224 Oct  4 17:09 .
drwxr-xr-x  4 vladislav  staff    128 Sep 29 19:31 ..
drwxr-xr-x  5 vladislav  staff    160 Oct  4 17:09 .ipynb_checkpoints
-rw-r--r--  1 vladislav  staff   5929 Oct  4 16:37 hw_lesson_2.ipynb
-rw-r--r--  1 vladislav  staff  10821 Oct  4 16:40 lesson_2_Numpy_Pandas.ipynb
-rw-r--r--  1 vladislav  staff   2528 Sep 29 19:43 lesson_2_welcome.ipynb
-rw-r--r--  1 vladislav  staff     77 Sep 29 19:41 script_01.py


In [58]:
!pwd

/Users/vladislav/GeekBrains/04_DataScience/lesson_2


In [ ]:
%load script_01.py

In [ ]:
%pycat script_01.py

## Lesson 2

### Numpy

In [2]:
import numpy as np

In [5]:
a = [i for i in range(10)]

In [6]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
b = np.array(a)

In [8]:
type(b)

numpy.ndarray

In [9]:
c = tuple(i for i in range(10))

In [10]:
c

(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)

In [11]:
cc = np.array(c)

In [12]:
cc

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
type(cc)

numpy.ndarray

In [14]:
aa = (0,1,2,3,4,5,6,7,8,9.9)

In [15]:
aaa = np.array(aa, dtype=int)

In [16]:
aaa

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
aaa = np.array(aa, dtype=float)

In [18]:
aaa

array([0. , 1. , 2. , 3. , 4. , 5. , 6. , 7. , 8. , 9.9])

In [19]:
aaa = np.array(aa, dtype=str)

In [20]:
aaa

array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9.9'], dtype='<U3')

In [21]:
aa = ['123', 1,2,3,4,5,6,7,8,9]

In [22]:
aaa = np.array(aa)

In [23]:
aaa

array(['123', '1', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U21')

In [24]:
aaa.dtype

dtype('<U21')

In [25]:
cc.dtype

dtype('int64')

In [26]:
aaa[0]

'123'

In [27]:
aaa[1]

'1'

In [28]:
aaa.ndim

1

In [29]:
aaa.shape

(10,)

#### 2D Array

In [44]:
w = np.array([
    [0,1,2,3,4],
    [i for i in range(11) if i not in [0,1,2,3,4,5]],
    [10,20,30,40,50]
])

In [45]:
w

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [10, 20, 30, 40, 50]])

In [46]:
w.ndim

2

In [47]:
w.shape

(3, 5)

In [48]:
w.size

15

In [50]:
w[2,2]

30

In [53]:
w[0:2,0:3]

array([[0, 1, 2],
       [6, 7, 8]])

In [54]:
w[:2,:3]

array([[0, 1, 2],
       [6, 7, 8]])

In [55]:
w[2:, 3:]

array([[40, 50]])

### Pandas

In [61]:
import pandas as pd
import numpy as np

In [62]:
a = [x for x in range(5)]

In [63]:
pd.Series(a)

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [65]:
pd.Series(a, index = [1,2,3,4,5])

1    0
2    1
3    2
4    3
5    4
dtype: int64

In [66]:
pd.Series(a , index = ['a','b','c','d','f'])

a    0
b    1
c    2
d    3
f    4
dtype: int64

In [70]:
from datetime import date
ind = [date(y,m,d) for y,m,d in [(2021, 1, 1), (2021, 1, 2), (2021, 3, 1), (2021, 1, 10), (2021, 3, 21)]]

In [72]:
b = pd.Series(a, index = ind)

In [73]:
b

2021-01-01    0
2021-01-02    1
2021-03-01    2
2021-01-10    3
2021-03-21    4
dtype: int64

In [74]:
b.index

Index([2021-01-01, 2021-01-02, 2021-03-01, 2021-01-10, 2021-03-21], dtype='object')

In [75]:
b.index[0].year

2021

In [76]:
b.index = pd.to_datetime(b.index, format = "%Y %m %d")

In [77]:
b.index

DatetimeIndex(['2021-01-01', '2021-01-02', '2021-03-01', '2021-01-10',
               '2021-03-21'],
              dtype='datetime64[ns]', freq=None)

In [78]:
b.index.year

Int64Index([2021, 2021, 2021, 2021, 2021], dtype='int64')

In [79]:
b.index.day

Int64Index([1, 2, 1, 10, 21], dtype='int64')

In [80]:
dd = {'1st': 0, '2st':1}

In [83]:
d = pd.Series(dd)

In [84]:
d.index

Index(['1st', '2st'], dtype='object')

In [85]:
d

1st    0
2st    1
dtype: int64

In [86]:
b.head

<bound method NDFrame.head of 2021-01-01    0
2021-01-02    1
2021-03-01    2
2021-01-10    3
2021-03-21    4
dtype: int64>

In [87]:
b.tail(2)

2021-01-10    3
2021-03-21    4
dtype: int64

In [88]:
b[2]

2

In [89]:
b[(b == 4) | (b % 3 == 0)]

2021-01-01    0
2021-01-10    3
2021-03-21    4
dtype: int64

In [92]:
b.append(pd.Series({'2021-01-02':88}))

2021-01-01 00:00:00     0
2021-01-02 00:00:00     1
2021-03-01 00:00:00     2
2021-01-10 00:00:00     3
2021-03-21 00:00:00     4
2021-01-02             88
dtype: int64

In [93]:
b.to_pickle('b.pkl')

In [94]:
bb = pd.read_pickle('b.pkl')

In [95]:
bb

2021-01-01    0
2021-01-02    1
2021-03-01    2
2021-01-10    3
2021-03-21    4
dtype: int64

#### DataFrame

In [97]:
df = pd.DataFrame({'col1': [1,2,3,4,5], 'col2': [x for x in ['a', 'b', 'c', 'd', 'e']]})

In [98]:
df

col1 col2
0     1    a
1     2    b
2     3    c
3     4    d
4     5    e

In [100]:
df.shape

(5, 2)

In [101]:
df.columns

Index(['col1', 'col2'], dtype='object')

In [102]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [105]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   col1    5 non-null      int64 
 1   col2    5 non-null      object
dtypes: int64(1), object(1)
memory usage: 208.0+ bytes


In [106]:
df.describe()

col1
count  5.000000
mean   3.000000
std    1.581139
min    1.000000
25%    2.000000
50%    3.000000
75%    4.000000
max    5.000000

In [107]:
df.head(2)

col1 col2
0     1    a
1     2    b

In [108]:
df.tail()

col1 col2
0     1    a
1     2    b
2     3    c
3     4    d
4     5    e

In [110]:
df.loc[2, 'col2']

'c'

In [111]:
df.to_csv('df.csv', sep=';', index = False)

In [112]:
df_new = pd.read_csv('df.csv', sep = ";")

In [113]:
df_new

col1 col2
0     1    a
1     2    b
2     3    c
3     4    d
4     5    e